/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

/**
 *
 * @author tisma
 */
public class gestionnaire extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestionnaire.class.getName());

    /**
     * Creates new form fournisseur
     */
    public gestionnaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btndeconnexion = new javax.swing.JButton();
        voirarticle = new javax.swing.JButton();
        voircommande = new javax.swing.JButton();
        voirclients = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Espace Gestionnaire");

        btndeconnexion.setText("Deconnexion");
        btndeconnexion.addActionListener(this::btndeconnexionActionPerformed);

        voirarticle.setText("Voir produit");
        voirarticle.addActionListener(this::voirarticleActionPerformed);

        voircommande.setText("Voir Commande");
        voircommande.addActionListener(this::voircommandeActionPerformed);

        voirclients.setText("Voir clients");
        voirclients.addActionListener(this::voirclientsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(voirarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(voirclients, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btndeconnexion)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(253, 253, 253))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btndeconnexion)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voirarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voirclients, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeconnexionActionPerformed
        // TODO add your handling code here:
        dispose();
        new login().show();
    }//GEN-LAST:event_btndeconnexionActionPerformed

    private void voircommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voircommandeActionPerformed
        // TODO add your handling code here:
        dispose();
        VoirCommandeGestionnaire vcg = new VoirCommandeGestionnaire();
        vcg.show();
    }//GEN-LAST:event_voircommandeActionPerformed

    private void voirarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirarticleActionPerformed
        // TODO add your handling code here:
        dispose();
        VoirProduitGestionnaire vpg = new VoirProduitGestionnaire();
        vpg.show();
    }//GEN-LAST:event_voirarticleActionPerformed

    private void voirclientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirclientsActionPerformed
        // TODO add your handling code here:
        dispose();
        VoirClientGestionnaire vcg = new VoirClientGestionnaire();
        vcg.show();
    }//GEN-LAST:event_voirclientsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voirarticle;
    private javax.swing.JButton voirclients;
    private javax.swing.JButton voircommande;
    // End of variables declaration//GEN-END:variables

    
}
