/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tisma
 */
public class VoirProduitGestionnaire extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoirProduitGestionnaire.class.getName());

    /**
     * Creates new form VoirArticleFournisseur
     */
    public VoirProduitGestionnaire() {
        initComponents();
        voirlisteproduit();
    }
    
    public Connection getconnexion(){
          Connection con;
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetlourd2.4","root","root");
                return con;
            }
            catch (SQLException e){
                System.out.println(e.getMessage());
                return null; //aucune connexion 
            }
       }
    
    public ArrayList<Produit> getlisteproduit(){
        ArrayList<Produit> listeproduit = new ArrayList<Produit>();
        Connection conn = getconnexion();
        String rqt = "SELECT nom_produit, description, prix, stock FROM produit";
        Statement st;
        ResultSet rs;
        
        try{
          st =  conn.createStatement();
          rs = st.executeQuery(rqt);
          Produit produit;
             while(rs.next()){
                 produit = new Produit(rs.getString("nom_produit"), rs.getString("description"), rs.getInt("prix"), rs.getString("stock"));
                 listeproduit.add(produit);
             }
        
        }catch (Exception e){
             System.out.println(e.getMessage());
        }
        return listeproduit;
    }
    
    public void voirlisteproduit(){
        ArrayList<Produit> list = getlisteproduit();
        DefaultTableModel model = (DefaultTableModel) tableproduit.getModel();
        Object[] row = new Object[4];
        for(int i = 0; i<list.size(); i++){
            row [0] = list.get(i).getnom_produit();
            row [1] = list.get(i).getdescription();
            row [2] = list.get(i).getprix();
            row [3] = list.get(i).getstock();
          model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduit = new javax.swing.JTable();
        voircommande = new javax.swing.JButton();
        voirclient = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        edtdescription = new javax.swing.JTextField();
        edtstock = new javax.swing.JTextField();
        edtprix = new javax.swing.JTextField();
        edtproduit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(880, 620));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Produit");

        jLabel2.setText("Gestionnaire");

        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(this::deconnexionActionPerformed);

        tableproduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit", "Description", "Stock", "Prix"
            }
        ));
        tableproduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproduit);

        voircommande.setText("Voir commande");
        voircommande.addActionListener(this::voircommandeActionPerformed);

        voirclient.setText("Voir client");
        voirclient.addActionListener(this::voirclientActionPerformed);

        modifier.setText("Modifier");
        modifier.addActionListener(this::modifierActionPerformed);

        ajouter.setText("Ajouter");
        ajouter.addActionListener(this::ajouterActionPerformed);

        supprimer.setText("Supprimer");
        supprimer.addActionListener(this::supprimerActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Stock:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Prix:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Produit:");

        menu.setText("Menu");
        menu.addActionListener(this::menuActionPerformed);

        reset.setText("Reset");
        reset.addActionListener(this::resetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deconnexion)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voirclient, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtprix, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reset)
                        .addGap(15, 15, 15)
                        .addComponent(modifier)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deconnexion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voirclient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtprix, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        
        dispose(); 
        login lg = new login();
        lg.show();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        try{
                
            Connection con = getconnexion();
            
            String produit = edtproduit.getText();
            String description = edtdescription.getText();
            String prix = edtprix.getText();
            String stock = edtstock.getText();
            
            String dr = "SELECT p.nom_produit FROM produit p INNER JOIN detailscommandes dc ON dc.id_produit=p.id_produit";
            Statement ps = con.createStatement();
            ResultSet rs = ps.executeQuery(dr);
                
                if (rs.next()) {
                    

                    String cmd ="SELECT id_commande FROM detailscommandes WHERE id_produit = (SELECT id_produit FROM produit WHERE nom_produit = ?)";
                    PreparedStatement cmdst = con.prepareStatement(cmd);
                    cmdst.setString(1, produit);
                    ResultSet cmdrs = cmdst.executeQuery();


                    String vf ="DELETE FROM detailscommandes WHERE id_produit = (SELECT id_produit FROM produit WHERE nom_produit = ?)";
                    PreparedStatement pc = con.prepareStatement(vf);
                    pc.setString(1, produit);
                    pc.executeUpdate();


                        while (cmdrs.next()) {

                            int id_commande = cmdrs.getInt("id_commande");

                            String gc = "DELETE FROM commande WHERE id_commande = ?";
                            PreparedStatement pscmd = con.prepareStatement(gc);
                            pscmd.setInt(1, id_commande);
                            pscmd.executeUpdate();
                        }
                    String sql =  "DELETE FROM produit  WHERE nom_produit = ?";
                    PreparedStatement pv = con.prepareStatement(sql);
                    pv.setString(1,produit);
                    pv.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, "Produit Supprimer avec succès !");

                    con.close();
                    pv.close();
                    
                }
                else {

                        String sql =  "DELETE FROM produit  WHERE nom_produit = ?";

                        PreparedStatement pv = con.prepareStatement(sql);

                        pv.setString(1,produit);
                        pv.executeUpdate();


                        JOptionPane.showMessageDialog(this, "Produit Supprimer avec succès !");

                        con.close();
                        pv.close();  
                }
            
            
            
        } 
        catch (SQLException e){
            System.out.println(e.getMessage());
        }
     
    }//GEN-LAST:event_supprimerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        
        try{
                
            Connection con = getconnexion();
            
            String sql = "UPDATE produit SET prix ='"+edtprix.getText() +"', stock = '"+edtstock.getText()+"' ";
            
            PreparedStatement ps = con.prepareStatement(sql);
            ps.executeUpdate();
            
         
            JOptionPane.showMessageDialog(this, "Produit Modifier avec succès !");
            
            con.close();
            ps.close();
            
        } 
        catch (SQLException e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_modifierActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        
        try{
                
            
            
            Connection con = getconnexion();
            
            String produit = edtproduit.getText();
            String description = edtdescription.getText();
            String prix = edtprix.getText();
            String stock = edtstock.getText();
            
            
            
            String sql = "INSERT INTO produit(nom_produit,description,prix,stock) VALUES (?, ?, ?, ?)";
            
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1,produit);
            ps.setString(2,description);
            ps.setString(3,prix);
            ps.setString(4,stock);
            ps.executeUpdate();
            
         
            JOptionPane.showMessageDialog(this, "Produit ajouter avec succès !");
            
            con.close();
            ps.close();
            
        } 
        catch (SQLException e){
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void voircommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voircommandeActionPerformed
        // TODO add your handling code here:
        
        dispose();
        VoirCommandeGestionnaire vcg = new VoirCommandeGestionnaire();
        vcg.show();
    }//GEN-LAST:event_voircommandeActionPerformed

    private void voirclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirclientActionPerformed
        // TODO add your handling code here:
        
        dispose();
        VoirClientGestionnaire vcg = new VoirClientGestionnaire();
        vcg.show();
    }//GEN-LAST:event_voirclientActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        dispose();
        gestionnaire gs = new gestionnaire();
        gs.show();
    }//GEN-LAST:event_menuActionPerformed

    private void tableproduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproduitMouseClicked
        // TODO add your handling code here:
        
        int i = tableproduit.getSelectedRow();
        TableModel model = tableproduit.getModel();

        edtproduit.setText(model.getValueAt(i, 0).toString());
        edtdescription.setText(model.getValueAt(i, 1).toString());
        edtprix.setText(model.getValueAt(i, 2).toString());
        edtstock.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tableproduitMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        edtproduit.setText("");
        edtdescription.setText("");
        edtprix.setText("");
        edtstock.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton deconnexion;
    private javax.swing.JTextField edtdescription;
    private javax.swing.JTextField edtprix;
    private javax.swing.JTextField edtproduit;
    private javax.swing.JTextField edtstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JButton modifier;
    private javax.swing.JButton reset;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tableproduit;
    private javax.swing.JButton voirclient;
    private javax.swing.JButton voircommande;
    // End of variables declaration//GEN-END:variables
}
