/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tisma
 */
public class VoirCommandeClient extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoirCommandeClient.class.getName());

    /**
     * Creates new form VoirCommandeMagasin
     */
    public VoirCommandeClient() {
        initComponents();
        voirlistecommandec();
    }
    
    public Connection getconnexion(){
          Connection con;
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetlourd2.4","root","root");
                return con;
            }
            catch (SQLException e){
                System.out.println(e.getMessage());
                return null; //aucune connexion 
            }
       }
    
    public ArrayList<Commandec> getlistecommandec(){
        ArrayList<Commandec> listecommandec = new ArrayList<Commandec>();
        Connection con = getconnexion();
        String rqt = "SELECT c.id_commande,p.nom_produit,c.date_commande,d.quantite,e.nom_etat,c.montant_total FROM commande c INNER JOIN detailscommandes d ON c.id_commande = d.id_commande INNER JOIN produit p ON p.id_produit = d.id_produit INNER JOIN etat e ON e.id_etat = c.id_etat";
        Statement st;
        ResultSet rs;
        try{
            st = con.createStatement();
            rs = st.executeQuery(rqt);
            Commandec commandec;
            while(rs.next()){
                commandec = new Commandec(rs.getInt("id_commande"),rs.getString("nom_produit"), rs.getString("date_commande"), rs.getInt("quantite"), rs.getString("nom_etat"),rs.getInt("montant_total"));
                listecommandec.add(commandec);
            }
        }catch (Exception e ){
                    System.out.println(e.getMessage() );
             }
        return listecommandec;
    }

    public void voirlistecommandec(){
        ArrayList<Commandec> list = getlistecommandec();
        DefaultTableModel model =  (DefaultTableModel) tablecommande.getModel();
        Object[] row = new Object[6];
        for(int i = 0; i<list.size() ; i++){
            
            row [0] = list.get(i).getid_commande();
            row [1] = list.get(i).getnom_produit();
            row [2] = list.get(i).getdate_commande();
            row [3] = list.get(i).getquantite();
            row [4] = list.get(i).getnom_etat();
            row [5] = list.get(i).getmontant_total();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        voirproduit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecommande = new javax.swing.JTable();
        edtdatec = new javax.swing.JTextField();
        edtproduit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        modifier = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        edtetatc = new javax.swing.JComboBox<>();
        edtnumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supprimer = new javax.swing.JButton();
        edtmontant = new javax.swing.JTextField();
        edtquantite = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Commande");

        jLabel2.setText("Client");

        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(this::deconnexionActionPerformed);

        voirproduit.setText("Voir produit");
        voirproduit.addActionListener(this::voirproduitActionPerformed);

        tablecommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n° commande", "Produit", "Date commande", "Quantité", "Etat", "Montant total"
            }
        ));
        tablecommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecommandeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecommande);

        edtproduit.addActionListener(this::edtproduitActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Quantité:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Montant total:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Etat:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Produit:");

        modifier.setText("Modifier");
        modifier.addActionListener(this::modifierActionPerformed);

        menu.setText("Menu");
        menu.addActionListener(this::menuActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Date :");

        edtetatc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------- Séléctionne état -------", "En cours", "Validé" }));

        edtnumero.addActionListener(this::edtnumeroActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("N°:");

        supprimer.setText("Supprimer");
        supprimer.addActionListener(this::supprimerActionPerformed);

        edtmontant.addActionListener(this::edtmontantActionPerformed);

        edtquantite.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deconnexion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(edtproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addComponent(edtdatec)
                                            .addComponent(edtnumero, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(edtmontant, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(edtetatc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(edtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(voirproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deconnexion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtdatec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(edtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtetatc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(edtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voirproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        
        dispose();
        login lg = new login();
        lg.show();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void voirproduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirproduitActionPerformed
        // TODO add your handling code here:
        dispose();
        VoirProduitClient vpc = new VoirProduitClient();
        vpc.show();
    }//GEN-LAST:event_voirproduitActionPerformed

    private void edtproduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtproduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtproduitActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
                
            if ("En cours".equals(edtetatc.getSelectedItem().toString()))  {
                   try{ 
                        Connection con = getconnexion();

                            String cmd ="SELECT stock FROM produit WHERE id_produit = (SELECT id_produit FROM detailscommandes WHERE id_commande ='"+edtnumero.getText()+"')";
                            PreparedStatement cmdst = con.prepareStatement(cmd);
                            ResultSet cmdrs = cmdst.executeQuery();

                                if (cmdrs.next()){

                                    int stock = cmdrs.getInt("stock");
                                    int quantite = (int) edtquantite.getValue();

                                        if (stock>=quantite){
                                            String sql = "UPDATE detailscommandes SET quantite = '"+edtquantite.getValue()+"' WHERE id_commande = '"+edtnumero.getText()+"'";
                                            PreparedStatement ps = con.prepareStatement(sql);
                                            ps.executeUpdate();
                                            
                                            JOptionPane.showMessageDialog(this, "Commande modifier avec succès!");
                                        }

                                        else {
                                            JOptionPane.showMessageDialog(this, "Commande ne pouvant être modifier car stock insufisant selon la quantité choisit !");
                                        }
                                }

                        con.close();
                        cmdst.close();
                    } 
                    catch (SQLException e){
                        System.out.println(e.getMessage());
                    }
           } else {
              JOptionPane.showMessageDialog(this, "Commande ne peut être modifier!");
           }
            
        
        
    }//GEN-LAST:event_modifierActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Client cl = new Client();
        cl.show();
    }//GEN-LAST:event_menuActionPerformed

    private void tablecommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecommandeMouseClicked
        // TODO add your handling code here:
        
        int i = tablecommande.getSelectedRow();
        TableModel model = tablecommande.getModel();
        edtnumero.setText(model.getValueAt(i, 0).toString());
        edtproduit.setText(model.getValueAt(i, 1).toString());
        edtdatec.setText(model.getValueAt(i, 2).toString());
        edtquantite.setValue(Integer.parseInt(model.getValueAt(i, 3).toString()));
        edtetatc.setSelectedItem(model.getValueAt(i, 4).toString());
        edtmontant.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tablecommandeMouseClicked

    private void edtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtnumeroActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        
    
            
        if ("En cours".equals(edtetatc.getSelectedItem().toString())){
             try{ 
                Connection con = getconnexion();
  
                String cmd ="SELECT id_commande FROM detailscommandes WHERE id_commande = (SELECT id_commande FROM commande WHERE id_commande = '"+  edtnumero.getText() +"')";
                PreparedStatement cmdst = con.prepareStatement(cmd);
                ResultSet cmdrs = cmdst.executeQuery();
            
            
                String vf ="DELETE FROM detailscommandes WHERE id_commande = (SELECT id_commande FROM commande WHERE id_commande ='"+  edtnumero.getText() +"')";
                PreparedStatement pc = con.prepareStatement(vf);
                pc.executeUpdate();
            
              
                String sql =  "DELETE FROM commande  WHERE id_commande ='"+  edtnumero.getText() +"' ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.executeUpdate();
                
                
  
                JOptionPane.showMessageDialog(this, "Commande Supprimer avec succès !");
                
                con.close();
                ps.close();
              
             }catch (SQLException e){
                 System.out.println(e.getMessage());
             }
        }else{
            JOptionPane.showMessageDialog(this, "Commande ne peut pas etre supprimer !");
        }
    
    }//GEN-LAST:event_supprimerActionPerformed

    private void edtmontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtmontantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtmontantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexion;
    private javax.swing.JTextField edtdatec;
    private javax.swing.JComboBox<String> edtetatc;
    private javax.swing.JTextField edtmontant;
    private javax.swing.JTextField edtnumero;
    private javax.swing.JTextField edtproduit;
    private javax.swing.JSpinner edtquantite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tablecommande;
    private javax.swing.JButton voirproduit;
    // End of variables declaration//GEN-END:variables
}