/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tisma
 */
public class VoirProduitClient extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoirProduitClient .class.getName());

    /**
     * Creates new form VoirProduitClient 
     */
    public VoirProduitClient () {
        initComponents();
        voirlisteproduit();
    }
    
    public Connection getconnexion(){
          Connection con;
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetlourd2.4","root","root");
                return con;
            }
            catch (SQLException e){
                System.out.println(e.getMessage());
                return null; //aucune connexion 
            }
       }
    
    public ArrayList<Produit> getlisteproduit(){
        ArrayList<Produit> listeproduit = new ArrayList<Produit>();
        Connection conn = getconnexion();
        String rqt = "SELECT nom_produit, description, prix, stock FROM produit";
        Statement st;
        ResultSet rs;
        
        try{
            st = conn.createStatement();
            rs = st.executeQuery(rqt);
            Produit produit;
            while(rs.next()){
                produit = new Produit(rs.getString("nom_produit"), rs.getString("description"), rs.getInt("prix"), rs.getString("stock"));
                listeproduit.add(produit);
            }
        }catch (Exception e ){
                    System.out.println(e.getMessage() );
             }
        return listeproduit;
            
       }
    
    public void voirlisteproduit(){
        ArrayList<Produit> list = getlisteproduit();
        DefaultTableModel model = (DefaultTableModel) tableproduit.getModel();
        Object[] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row [0] = list.get(i).getnom_produit();
            row [1] = list.get(i).getdescription();
            row [2] = list.get(i).getprix();
            row [3] = list.get(i).getstock();
            
            model.addRow(row);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voircommande = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduit = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voircommande.setText("Voir commande");
        voircommande.addActionListener(this::voircommandeActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Produit");

        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(this::deconnexionActionPerformed);

        tableproduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit", "Description", "Prix", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableproduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproduit);

        jLabel2.setText("Client");

        menu.setText("Menu");
        menu.addActionListener(this::menuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deconnexion)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(363, 363, 363))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(257, 257, 257))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deconnexion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voircommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voircommandeActionPerformed
        // TODO add your handling code here:
        
        dispose();
        VoirCommandeClient vcc = new VoirCommandeClient();
        vcc.show();
    }//GEN-LAST:event_voircommandeActionPerformed

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        dispose();
        login lg = new login(); // ()--> faire appel
        lg.show();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Client cl = new Client();
        cl.show();
    }//GEN-LAST:event_menuActionPerformed

    private void tableproduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproduitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableproduitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JTable tableproduit;
    private javax.swing.JButton voircommande;
    // End of variables declaration//GEN-END:variables
}
