/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author tisma
 */
public class VoirCommandeGestionnaire extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoirCommandeGestionnaire.class.getName());

    /**
     * Creates new form VoirCommandeFournisseur
     */
    public VoirCommandeGestionnaire() {
        initComponents();
        voirlistecommande();
    }
    
    public Connection getconnexion(){
          Connection con;
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetlourd2.4","root","root");
                return con;
            }
            catch (SQLException e){
                System.out.println(e.getMessage());
                return null; //aucune connexion 
            }
       }
    
    public ArrayList<Commande> getlistecommande(){
        ArrayList<Commande> listecommande = new ArrayList<Commande>();
        Connection con = getconnexion();
        String rqt = "SELECT c.id_commande,cs.nom,p.nom_produit,c.date_commande,d.quantite,e.nom_etat,c.montant_total FROM commande c INNER JOIN clients cs ON cs.id_client = c.id_client INNER JOIN detailscommandes d ON c.id_commande = d.id_commande INNER JOIN produit p ON p.id_produit = d.id_produit INNER JOIN etat e ON e.id_etat = c.id_etat";
        Statement st;
        ResultSet rs;
        try{
            st = con.createStatement();
            rs = st.executeQuery(rqt);
            Commande commande;
            while(rs.next()){
                commande = new Commande(rs.getInt("id_commande"),rs.getString("nom"), rs.getString("nom_produit"), rs.getString("date_commande"), rs.getInt("quantite"), rs.getString("nom_etat"),rs.getInt("montant_total"));
                listecommande.add(commande);
            }
        }catch (Exception e ){
                    System.out.println(e.getMessage() );
             }
        return listecommande;
    }

    public void voirlistecommande(){
        ArrayList<Commande> list = getlistecommande();
        DefaultTableModel model =  (DefaultTableModel) TableCommandeGestionnaire.getModel();
        Object[] row = new Object[7];
        for(int i = 0; i<list.size() ; i++){
            
            row [0] = list.get(i).getid_commande();
            row [1] = list.get(i).getnom();
            row [2] = list.get(i).getnom_produit();
            row [3] = list.get(i).getdate_commande();
            row [4] = list.get(i).getquantite();
            row [5] = list.get(i).getnom_etat();
            row [6] = list.get(i).getmontant_total();
            
            model.addRow(row);
        }
        
       
    }
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voirclient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCommandeGestionnaire = new javax.swing.JTable();
        deconnexion = new javax.swing.JButton();
        voirproduit = new javax.swing.JButton();
        supprimerCommande = new javax.swing.JButton();
        modifierCommande = new javax.swing.JButton();
        edtproduit = new javax.swing.JTextField();
        edtquantite = new javax.swing.JTextField();
        edtmontant = new javax.swing.JTextField();
        edtdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edtnom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edtetat = new javax.swing.JComboBox<>();
        menu = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        edtnumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Commande");

        jLabel2.setText("Gestionnaire");

        voirclient.setText("Voir client");
        voirclient.addActionListener(this::voirclientActionPerformed);

        TableCommandeGestionnaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n° commande", "Nom Client", "Produit", "Date_commande", "Quantité", "Etat", "Montant Total"
            }
        ));
        TableCommandeGestionnaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCommandeGestionnaireMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCommandeGestionnaire);

        deconnexion.setText("déconnexion");
        deconnexion.addActionListener(this::deconnexionActionPerformed);

        voirproduit.setText("Voir Produit");
        voirproduit.addActionListener(this::voirproduitActionPerformed);

        supprimerCommande.setText("Supprimer");
        supprimerCommande.setPreferredSize(new java.awt.Dimension(120, 40));
        supprimerCommande.addActionListener(this::supprimerCommandeActionPerformed);

        modifierCommande.setText("Modifier");
        modifierCommande.setPreferredSize(new java.awt.Dimension(120, 40));
        modifierCommande.addActionListener(this::modifierCommandeActionPerformed);

        edtproduit.setPreferredSize(new java.awt.Dimension(64, 22));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Date commande:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Quantité:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Produit:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Montant total:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Etat:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nom Client:");

        edtetat.setMaximumRowCount(3);
        edtetat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------- Séléctionne état -------", "En cours", "Validé", "" }));
        edtetat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menu.setText("Menu");
        menu.addActionListener(this::menuActionPerformed);

        reset.setText("Reset");
        reset.addActionListener(this::resetActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("N° commande:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voirproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voirclient, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel4)))
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtetat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modifierCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(supprimerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deconnexion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voirproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voirclient, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtetat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifierCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        dispose();
        login lg = new login();
        lg.show();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void voirproduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirproduitActionPerformed
        // TODO add your handling code here:
        dispose();
        VoirProduitGestionnaire vpg = new VoirProduitGestionnaire(); // création de la vue en lien avec la class VoirProduitGestionnaire qui stockera l'objet VoirProduitGestionnaire ( constructeur)
        vpg.show();
    }//GEN-LAST:event_voirproduitActionPerformed

    private void voirclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirclientActionPerformed
        // TODO add your handling code here:
        
        dispose();
        VoirClientGestionnaire vcg = new VoirClientGestionnaire(); 
        vcg.show();
    }//GEN-LAST:event_voirclientActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        dispose();
        gestionnaire gs = new gestionnaire();
        gs.show();
    }//GEN-LAST:event_menuActionPerformed

    private void TableCommandeGestionnaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCommandeGestionnaireMouseClicked
        // TODO add your handling code here:
        
        int i = TableCommandeGestionnaire.getSelectedRow();
        TableModel model = TableCommandeGestionnaire.getModel();
        edtnumero.setText(model.getValueAt(i, 0).toString());
        edtnom.setText(model.getValueAt(i, 1).toString());
        edtproduit.setText(model.getValueAt(i, 2).toString());
        edtdate.setText(model.getValueAt(i, 3).toString());
        edtquantite.setText(model.getValueAt(i, 4).toString());
        edtetat.setSelectedItem(model.getValueAt(i, 5).toString());
        edtmontant.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_TableCommandeGestionnaireMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
        edtnumero.setText("");
        edtnom.setText("");
        edtproduit.setText("");
        edtdate.setText("");
        edtquantite.setText("");
        edtetat.setSelectedItem("------- Séléctionne état -------");
        edtmontant.setText("");  
        TableCommandeGestionnaire.clearSelection();
    }//GEN-LAST:event_resetActionPerformed

    private void modifierCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierCommandeActionPerformed
        // TODO add your handling code here:
        
        try{
                
            Connection con = getconnexion();
            
            
            String sql = "UPDATE commande SET id_etat = (SELECT id_etat FROM etat WHERE nom_etat = '"+ edtetat.getSelectedItem() +"') WHERE id_commande = '"+ edtnumero.getText()+ "'";
            
            PreparedStatement ps = con.prepareStatement(sql);
            ps.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Commande Modifier avec succès !");
            
            
            
            con.close();
            ps.close();
            
        } 
        catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_modifierCommandeActionPerformed

    private void supprimerCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerCommandeActionPerformed
        // TODO add your handling code here:
       try{ 
            Connection con = getconnexion();
  
                String cmd ="SELECT id_commande FROM detailscommandes WHERE id_commande = (SELECT id_commande FROM commande WHERE id_commande = '"+  edtnumero.getText() +"')";
                PreparedStatement cmdst = con.prepareStatement(cmd);
                ResultSet cmdrs = cmdst.executeQuery();
            
            
                String vf ="DELETE FROM detailscommandes WHERE id_commande = (SELECT id_commande FROM commande WHERE id_commande ='"+  edtnumero.getText() +"')";
                PreparedStatement pc = con.prepareStatement(vf);
                pc.executeUpdate();
            
              
                String sql =  "DELETE FROM commande  WHERE id_commande ='"+  edtnumero.getText() +"' ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.executeUpdate();
                
                
  
                JOptionPane.showMessageDialog(this, "Commande Supprimer avec succès !");
                
                con.close();
                ps.close();
        } 
        catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_supprimerCommandeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCommandeGestionnaire;
    private javax.swing.JButton deconnexion;
    private javax.swing.JTextField edtdate;
    private javax.swing.JComboBox<String> edtetat;
    private javax.swing.JTextField edtmontant;
    private javax.swing.JTextField edtnom;
    private javax.swing.JTextField edtnumero;
    private javax.swing.JTextField edtproduit;
    private javax.swing.JTextField edtquantite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JButton modifierCommande;
    private javax.swing.JButton reset;
    private javax.swing.JButton supprimerCommande;
    private javax.swing.JButton voirclient;
    private javax.swing.JButton voirproduit;
    // End of variables declaration//GEN-END:variables
}
