/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tisma
 */
public class VoirClientGestionnaire extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoirClientGestionnaire.class.getName());

    /**
     * Creates new form VoirClientGestionnaire
     */
    public VoirClientGestionnaire() {
        initComponents(); // activation des composants graphique
        voirclientdanstable(); // activation automatique des lors que le fenetre s'ouvre
    }

    public Connection getconnexion(){
          Connection con;
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetlourd2.4","root","root");
                return con;
            }
            catch (SQLException e){
                System.out.println(e.getMessage());
                return null; //aucune connexion 
            }
       }
    
    public ArrayList<User> getuserlist(){
    
        ArrayList<User> userlist = new ArrayList<User>();
        Connection conn = getconnexion();
        String query = "SELECT nom, prenom, email FROM clients";
        Statement st; // envoie requete 
        ResultSet rs; // contient le resultat de la requete 
        
        try {
          st = conn.createStatement();
          rs = st.executeQuery(query);
          User user;
            while(rs.next()){
                user = new User(rs.getString("nom"),rs.getString("prenom"),rs.getString("email"));
                userlist.add(user);
            }
       
        }catch (Exception e){
             System.out.println(e.getMessage());
        }
        return userlist; // envoie de tous les resultat 
    }
    
    public void voirclientdanstable(){
    
          ArrayList<User> list = getuserlist(); // recuperation des user
          DefaultTableModel model = (DefaultTableModel) tableclient.getModel();
          Object[] row = new Object[3];
          for (int i = 0; i< list.size() ;i++){
              row [0] = list.get(i).getnom();
              row [1] = list.get(i).getprenom();
              row [2] = list.get(i).getemail();
              
            model.addRow(row);
             }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        voirproduit = new javax.swing.JButton();
        voircommande = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableclient = new javax.swing.JTable();
        ajoutergestionnaire = new javax.swing.JButton();
        edtlogin = new javax.swing.JTextField();
        edtmail = new javax.swing.JTextField();
        edtprenom = new javax.swing.JTextField();
        edtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtpassword = new javax.swing.JTextField();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 660));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Client");

        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(this::deconnexionActionPerformed);

        voirproduit.setText("Voir produit");
        voirproduit.addActionListener(this::voirproduitActionPerformed);

        voircommande.setText("Voir commande");
        voircommande.setPreferredSize(new java.awt.Dimension(160, 41));
        voircommande.addActionListener(this::voircommandeActionPerformed);

        tableclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Email"
            }
        ));
        tableclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableclientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableclient);

        ajoutergestionnaire.setText("Ajouter");
        ajoutergestionnaire.setPreferredSize(new java.awt.Dimension(120, 40));
        ajoutergestionnaire.addActionListener(this::ajoutergestionnaireActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Prénom:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Login:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nom:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Mot de passe:");

        jLabel4.setText("Gestionnaire");

        menu.setText("Menu");
        menu.addActionListener(this::menuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deconnexion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ajoutergestionnaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtprenom)
                                    .addComponent(edtmail)
                                    .addComponent(edtlogin)
                                    .addComponent(edtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtpassword))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voirproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(deconnexion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voirproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voircommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(edtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(ajoutergestionnaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        dispose();
        login lg = new login();
        lg.show();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void ajoutergestionnaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutergestionnaireActionPerformed
        // TODO add your handling code here:
        
        try{
                
            Connection con = getconnexion();
            
            String nom = edtnom.getText();
            String prenom = edtprenom.getText();
            String email = edtmail.getText();
            String login = edtlogin.getText();
            String mdp = edtpassword.getText();
            
            String sql = "INSERT INTO clients(nom,prenom,email,login,mdp,id_types_fonction) VALUES (?, ?, ?, ?,?,2)";
            
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1,nom);
            ps.setString(2,prenom);
            ps.setString(3,email);
            ps.setString(4,login);
            ps.setString(5,mdp);
            ps.executeUpdate();
            
         
            JOptionPane.showMessageDialog(this, "Gestionnaire Ajouter avec succès !");
            
            con.close();
            ps.close();
            
        } 
        catch (SQLException e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_ajoutergestionnaireActionPerformed

    private void voirproduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirproduitActionPerformed
        // TODO add your handling code here:
        dispose();
        VoirProduitGestionnaire vcg = new VoirProduitGestionnaire();
        vcg.show();
    }//GEN-LAST:event_voirproduitActionPerformed

    private void voircommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voircommandeActionPerformed
        // TODO add your handling code here:
        
        dispose();
        VoirCommandeGestionnaire vcg = new VoirCommandeGestionnaire();
        vcg.show();
    }//GEN-LAST:event_voircommandeActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        dispose();
        gestionnaire gs = new gestionnaire();
        gs.show();
    }//GEN-LAST:event_menuActionPerformed

    private void tableclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableclientMouseClicked
        // TODO add your handling code here:
        //int i = tableclient.getSelectedRow();
        //TableModel model = tableclient.getModel();

        //edtnom.setText(model.getValueAt(i, 0).toString());
        //edtprenom.setText(model.getValueAt(i, 1).toString());
        //edtmail.setText(model.getValueAt(i, 2).toString());
        
        
        
    }//GEN-LAST:event_tableclientMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutergestionnaire;
    private javax.swing.JButton deconnexion;
    private javax.swing.JTextField edtlogin;
    private javax.swing.JTextField edtmail;
    private javax.swing.JTextField edtnom;
    private javax.swing.JTextField edtpassword;
    private javax.swing.JTextField edtprenom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JTable tableclient;
    private javax.swing.JButton voircommande;
    private javax.swing.JButton voirproduit;
    // End of variables declaration//GEN-END:variables
}
